# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: titlebook.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='titlebook.proto',
  package='tutorial',
  serialized_pb='\n\x0ftitlebook.proto\x12\x08tutorial\"\x1a\n\tTitleList\x12\r\n\x05title\x18\x01 \x03(\t\"\x14\n\x06IdList\x12\n\n\x02id\x18\x01 \x03(\x05')




_TITLELIST = _descriptor.Descriptor(
  name='TitleList',
  full_name='tutorial.TitleList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='tutorial.TitleList.title', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=55,
)


_IDLIST = _descriptor.Descriptor(
  name='IdList',
  full_name='tutorial.IdList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tutorial.IdList.id', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=57,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['TitleList'] = _TITLELIST
DESCRIPTOR.message_types_by_name['IdList'] = _IDLIST

class TitleList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TITLELIST

  # @@protoc_insertion_point(class_scope:tutorial.TitleList)

class IdList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _IDLIST

  # @@protoc_insertion_point(class_scope:tutorial.IdList)


# @@protoc_insertion_point(module_scope)
